#ifndef __GUI_CONFIGS_HPP__
#define __GUI_CONFIGS_HPP__
#include "vec2.hpp"

#define WIDGET_EDITOR_BUFFER_NAME_WRITE_OFFSET Vec2(3,0)
#define WIDGET_BORDER_THICK 0
#define WIDGET_FLOAT_GAP_BETWEEN_USER_COMPL 0.5
#define WIDGET_FLOAT_DATA_DRAW_OFFSET Vec2(4,1)
#define WIDGET_LAYER_DEFAULT 0
#define WIDGET_FLOAT_LAYER_DEFAULT 1
#define WIDGET_FLOAT_DEFAULT_ROW_AMOUNT 2

namespace GuiConstants {
    const std::string CMD_STRING = "Cmd";
}

#endif // __GUI_CONFIGS_HPP__
